### ISSUE TITLE
Error on last

### ISSUE THREAD

**Issue by L-Luciano** [gregberge/content-range#4]
Hi,

There is an error at this line : 
var last = options.last || (options.first + options.limit - 1);

If last = 0 (case of 1 element => 0-0/1), it doesn't work
fix :
var last = options.last ?? (options.first + options.limit - 1);

**Comment by gregberge** [comment]
Yeah you are right, could you submit a fix?

**Comment by L-Luciano** [comment]
Yes of course,
It's done

**Comment by gregberge** [comment]
Fixed.
