### ISSUE TITLE
Support range format

### ISSUE THREAD

**Issue by slavchev** [gregberge/content-range#9]
Does this parser support `Range` format as specified on Mozilla site?

```
Range: <unit>=<range-start>-
Range: <unit>=<range-start>-<range-end>
Range: <unit>=<range-start>-<range-end>, <range-start>-<range-end>
Range: <unit>=<range-start>-<range-end>, <range-start>-<range-end>, <range-start>-<range-end>
Range: <unit>=-<suffix-length>
```

You can see `Range` header described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range).

**Comment by gregberge** [comment]
No, it supports [Content-Range header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range) only.
